=== meherchandan/Tajawal_Backend_Test/src/test/resources/hotel-search.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "type": {
      "type": "string"
    },
    "query": {
      "type": "string"
    },
    "queryParameters": {
      "type": "string"
    },
    "queryParametersObj": {
      "type": "object",
      "properties": {
        "sortBy": {
          "type": "string"
        },
        "isGeo": {
          "type": "integer"
        },
        "hId": {
          "type": "string"
        },
        "placeId": {
          "type": "string"
        },
        "types": {
          "type": "array",
          "items": {}
        }
      },
      "required": [
        "sortBy",
        "isGeo",
        "hId",
        "placeId",
        "types"
      ]
    },
    "isCountry": {
      "type": "boolean"
    }
  },
  "required": [
    "type",
    "query",
    "queryParameters",
    "queryParametersObj",
    "isCountry"
  ]
}

=== meherchandan/Tajawal_Backend_Test/target/hotel-search/response2.json
{"queryParameters":"sortBy=distanceScore&isGeo=1&hId=&placeId=ChIJD7fiBh9u5kcRYJSMaMOCCwQ&types=","isCountry":false,"query":"paris\/24-08-2019\/31-08-2019\/2_adult,1_child,3_age\/3_adult","queryParametersObj":{"hId":"","types":[],"placeId":"ChIJD7fiBh9u5kcRYJSMaMOCCwQ","sortBy":"distanceScore","isGeo":1},"type":"hotel"}
